#!/bin/bash
# Bring up VMs and deploy k8s with vortex-installer and kubespray 
#
# Dependencies:
# - make
# - virtualbox
# - vagrant

vagrant plugin install vagrant-vbguest vagrant-disksize
vagrant up

vagrant ssh node-1 --command 'git clone https://github.com/linkernetworks/vortex-installer.git'

vagrant ssh node-1 --command 'mkdir -p vortex-installer/inventory/keys'

cp id_rsa vortex-installer/inventory/keys/id_rsa
cp id_rsa.pub vortex-installer/inventory/keys/id_rsa.pub

vagrant ssh node-1 --command 'cd vortex-installer && make ansible all'
