#!/bin/bash

apt-get update && \
  apt-get install -y curl \
  apt-transport-https \
  ca-certificates \
  software-properties-common \
  python-pip \
  jq && \
  curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add - && \
  apt-key fingerprint 0EBFCD88 && \
  add-apt-repository -y "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" && \
  apt-get update && \
  apt-get install -y --allow-downgrades docker-ce=17.03.2~ce-0~ubuntu-xenial

export LC_ALL=C && \
  pip install yq

add-apt-repository -y ppa:gluster/glusterfs-3.13 && \
  apt-get update && \
  apt-get install -y \
  glusterfs-server \
  thin-provisioning-tools \
  lvm2 \
  xfsprogs
